# Notion Pages Download Configuration
# Add pages you want to download here

config:
  # Global settings (can be overridden per page later)
  output_formats: ["markdown", "png", "pdf"]  # Formats to generate (markdown is default)
  s3_bucket: "snowplow-qa-notion-pages"
  s3_prefix: "notion-pages"
  refresh_hours: 24  # Only re-download if older than this many hours
  force_refresh: false  # Set to true to ignore cache and force re-download
  
pages:
  - url: "https://www.notion.so/keep-in-the-snow/Git-1c207af295a2807a9d1ecf578d1465ea"
    name: "git"  # Used for filename generation
    subpages: false  # Set to true to include child pages
    
  - url: "https://www.notion.so/keep-in-the-snow/f7588c331ea846aabd0e25c5c4a35d0b"
    name: "postmortems"  # Used for filename generation
    subpages: true  # Include child pages and database records

  - url: "https://www.notion.so/keep-in-the-snow/SnowStorm-25-07-1c207af295a280658cf7e90071f477c1"
    name: "snowstorm"  # Used for filename generation
    subpages: false 
    
# Available options per page:
# - subpages: true/false - Include child pages and database records (default: false)
# - output_formats: ["markdown"] or ["png", "pdf"] or ["markdown", "png", "pdf"]
# - s3_bucket: "custom-bucket" (overrides global setting)

# Global cache options:
# - refresh_hours: Only re-download if older than this many hours (default: 24)
# - force_refresh: Set to true to ignore cache and force re-download all pages